### ISSUE TITLE
newlines aren't placed into quotes

### ISSUE THREAD

**Issue by aCuteLittleBox** [flutterflies/QuoteMe#2]
if you have a quote that has any newlines in it, the quote will show up without any newlines in it when called

**Comment by flutterflies** [comment]
In discordrb (I'm not sure how the general discord api handles this) arguments are sent as an array of strings with all separating whitespace removed, I'm not sure if there is a way for me to be able to preserve things like newlines

**Comment by aCuteLittleBox** [comment]
if it's sent as an array of strings by default i don't think it'd be possible then, sadly..
Each and every piece of whitespace between the strings has the potential to be a space, tab, or newline. The best you could do might just be guessing, which i feel would produce nonsensical output more often than not :(
